version: '3.2'

services:
  dashboard:
    build :
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: dashboard
    restart: unless-stopped
    networks:
      - dashboard-network
    volumes:
      - ./:/var/www/app
    environment:
      PHP_ENABLE_XDEBUG: 1

  nginx-dashboard:
    container_name: nginx-dashboard
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - dashboard-network
    volumes:
      - ./docker/conf/nginx/site.conf:/etc/nginx/sites-enabled/site.conf
      - ./docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app

networks:
  dashboard-network:
    driver: bridge